version: '3.5'
services:
  nodejs:
    container_name: node
    build:
      context: ./
#    environment:
#      - NODE_ENV=dev
    volumes:
#      - ./:/usr/src/app/
      - ./.env:/usr/src/app/.env
    restart: always
    ports:
      - "8080:8080"
  mongo:
    container_name: mongo
    image: mongo:3.6
    volumes:
      - ./db:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

